
package org.jboss.jbossas.quickstarts.wshelloworld.helloworld;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldService", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloResponse")
    public String sayHello();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToName", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloToName")
    @ResponseWrapper(localName = "sayHelloToNameResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloToNameResponse")
    public String sayHelloToName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMonthEndDate", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthEndDate")
    @ResponseWrapper(localName = "getMonthEndDateResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthEndDateResponse")
    public String getMonthEndDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMonthEndDay", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthEndDay")
    @ResponseWrapper(localName = "getMonthEndDayResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthEndDayResponse")
    public String getMonthEndDay(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToNames", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloToNames")
    @ResponseWrapper(localName = "sayHelloToNamesResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloToNamesResponse")
    public String sayHelloToNames(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHelloToJay", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloToJay")
    @ResponseWrapper(localName = "sayHelloToJayResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.SayHelloToJayResponse")
    public String sayHelloToJay();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMonthStartDay", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthStartDay")
    @ResponseWrapper(localName = "getMonthStartDayResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthStartDayResponse")
    public String getMonthStartDay(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMonthStartDate", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthStartDate")
    @ResponseWrapper(localName = "getMonthStartDateResponse", targetNamespace = "http://www.jboss.org/jbossas/quickstarts/wshelloworld/HelloWorld", className = "org.jboss.jbossas.quickstarts.wshelloworld.helloworld.GetMonthStartDateResponse")
    public String getMonthStartDate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
